# Generated by Django 5.0.6 on 2024-06-26 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('rated', models.CharField(max_length=10)),
                ('released', models.CharField(max_length=255)),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('metascore', models.CharField(max_length=10)),
                ('imdbrating', models.CharField(max_length=10)),
                ('imdbvotes', models.CharField(max_length=20)),
                ('imdbid', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('dvd', models.CharField(blank=True, max_length=50, null=True)),
                ('boxoffice', models.CharField(blank=True, max_length=50, null=True)),
                ('production', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('response', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=50)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.movie')),
            ],
        ),
    ]
