# Generated by Django 5.0.6 on 2024-06-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('rated', models.CharField(max_length=10)),
                ('released', models.DateField()),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('metascore', models.CharField(max_length=10)),
                ('imdb_rating', models.CharField(max_length=10)),
                ('imdb_votes', models.CharField(max_length=20)),
                ('imdb_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('dvd', models.CharField(blank=True, max_length=50, null=True)),
                ('box_office', models.CharField(blank=True, max_length=50, null=True)),
                ('production', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('response', models.CharField(max_length=10)),
                ('ratings', models.ManyToManyField(to='api.rating')),
            ],
        ),
    ]
