# Generated by Django 5.0.6 on 2024-06-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='metascore',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
