# Generated by Django 5.0.6 on 2024-06-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_movie_actors_alter_movie_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
