from django.db import models

class Movie(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    year = models.CharField(max_length=10, null=True, blank=True)
    rated = models.CharField(max_length=10, null=True, blank=True)
    released = models.CharField(max_length=255, null=True, blank=True)
    runtime = models.CharField(max_length=50, null=True, blank=True)
    genre = models.CharField(max_length=255, null=True, blank=True)
    director = models.CharField(max_length=255, null=True, blank=True)
    writer = models.CharField(max_length=255, null=True, blank=True)
    actors = models.TextField(null=True, blank=True)
    plot = models.TextField(null=True, blank=True)
    language = models.CharField(max_length=255, null=True, blank=True)
    country = models.CharField(max_length=255, null=True, blank=True)
    awards = models.TextField(null=True, blank=True)
    poster = models.URLField(null=True, blank=True)
    metascore = models.CharField(max_length=10, null=True, blank=True)
    imdbrating = models.CharField(max_length=10, null=True, blank=True)
    imdbvotes = models.CharField(max_length=20, null=True, blank=True)
    imdbid = models.CharField(max_length=50, null=True, blank=True)
    type = models.CharField(max_length=50, null=True, blank=True)
    dvd = models.CharField(max_length=50, null=True, blank=True)
    boxoffice = models.CharField(max_length=50, null=True, blank=True)
    production = models.CharField(max_length=255, null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    response = models.CharField(max_length=10)
